# choose docker version
version: '3' 

# configure services
services:
  # node service
  node-app:
    container_name: node-app
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - "mongo"
      - "caddy"
  
  # mongodb service
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  # caddy service
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: